### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by Mailaender** [linuxmint/xedit#2]
I was about to package this for @openSUSE, but sadly `xedit` already exists as in https://en.wikipedia.org/wiki/X11_Xedit and is also already included in the distribution https://build.opensuse.org/package/show/openSUSE:Factory/xedit so it will clash when both packages claim `/usr/bin/xedit`. It might be best to rename at this early stage I assume.

**Comment by Timmythepirate** [comment]
I also think that renaming would be the best idea. Also, **x-** seems like a poor prefix to use, since it is the common prefix for programs that are associated with X11,e.g., `xterm`

**Comment by leigh123linux** [comment]
This will also cause issues in debian and ubuntu

https://packages.debian.org/jessie/amd64/x11-apps/filelist

**Comment by clefebvre** [comment]
It could be renamed to xeditor I guess.

**Comment by sprintcowboy** [comment]
How about naming the x apps m apps instead?
Such as medit.
Just a thought.

**Comment by clefebvre** [comment]
x connotes that X11 common base and it also sounds like "ex"... as in that's how it was "before".  Whatever letter you pick you'll run into similar issues... mplayer anyone? :)

**Comment by sprintcowboy** [comment]
Forgot about mplayer.
How about X instead of x?

**Comment by clefebvre** [comment]
Using a capital X would only partially solve the issue.... it's tedious to type, people copying the command (from IRC or tutorials) might miss the case and end up running the X11 editor, and depending on the distribution the package names might or might not be case-sensitive.

There's "xed" which is short and would work very well. It was used in 2000 by an XML editor which looks to be discontinued now. It's not present in Debian. If it's not packaged in other distributions then we can use that name.

Failing that xeditor is probably the most straight forward solution.

**Comment by clefebvre** [comment]
No sign of xed in OpenSUSE and Fedora either as far as I can see.

**Comment by Timmythepirate** [comment]
+1 for xed

**Comment by sprintcowboy** [comment]
+2 for xed

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xedit/commit/16eacdc3f4fbebf48d41b7b8c237993de472ce5b

**Comment by clefebvre** [comment]
We'll rename the github project also accordingly. Sorry for the inconvenience and see you at the new URL.
